### ISSUE TITLE
Парсеры

### ISSUE THREAD

**Issue by fl0w3rs** [CrazyXacker/AniLabX-Lite-Desktop#1]
Приветствую. Будут ли в приложение добавлены парсеры как в мобильном? Откуда сейчас парсится контент?

**Comment by CrazyXacker** [comment]
@fl0w3rs Lite не умеет работать с парсерами. Следовательно, парсеры добавлены не будут
В данный момент в активной разработке старшая версия приложения с системой парсеров как в мобильном приложении. Сроков ее выхода я назвать не могу

**Comment by fl0w3rs** [comment]
Отлично, спасибо за ответ.
