### ISSUE TITLE
Перестал запускаться

### ISSUE THREAD

**Issue by HaoHeim** [CrazyXacker/AniLabX-Lite-Desktop#2]
Без какой явной причины приложение перестало работать. При запуске ничего не появляется.
До сегодняшнего дня всё работало. Из обновлений только видеодрайвер и джава библиотеки. Есть какие либо рекомендации?

**Comment by CrazyXacker** [comment]
@HaoHeim напишите на почту anilabx.supp[собака]gmail.com. Нужно от вас получить несколько файлов для уточнения проблемы
