### ISSUE TITLE
Версия для Linux не запускается

### ISSUE THREAD

**Issue by ANDRoid7890** [CrazyXacker/AniLabX-Lite-Desktop#3]
Использую дистрибутив Manjaro x64

**Comment by vanja-san** [comment]
У меня на Windows 10 тоже не запускается, хотелось бы знать требования и что должно быть установлено для запуска, так не понятно.

**Comment by PanPrizrak** [comment]
> Использую дистрибутив Manjaro x64

Подскажите, пожалуйста, как его запустить?

**Comment by CrazyXacker** [comment]
@ANDRoid7890 @PanPrizrak дистрибутивы используют libc или musl?
@vanja-san требования простые: х64 система и запуск от админа (приложение само запросит). Также, приложение нужно размещать в папке, в которой у него будут права на чтение/запись. Ну и графический ускоритель с поддержкйо опенгл/директх

**Comment by PanPrizrak** [comment]
> @ANDRoid7890 @PanPrizrak дистрибутивы используют libc или musl?
> @vanja-san требования простые: х64 система и запуск от админа (приложение само запросит). Также, приложение нужно размещать в папке, в которой у него будут права на чтение/запись. Ну и графический ускоритель с поддержкйо опенгл/директх

Ubuntu GLIBC 2.31-0ubuntu9.2

**Comment by CrazyXacker** [comment]
@PanPrizrak я правильно понимаю, что у вас убунта 9.2?
к сожалению, проверить все дистрибутивы у меня нет возможности. образ собирал на стандартном Ubuntu 20.04 LTS в WSL, а тестировал на Linux Mint 20 Ulyana на основе Ubuntu 20.04. есть отзывы по работе в Arch и OpenSuse

@vanja-san @PanPrizrak @ANDRoid7890 если не затруднит, создайте возле приложения пустой файл log без расширения и запустите приложение. возле него должны появиться два txt файла. отошлите их на почту anilabx.supp[собака]gmail.com с темой AniLabX Lite. после этого постараюсь более подробно ответить на вопрос почему не работает и исправлю проблему, если это возможно

**Comment by PanPrizrak** [comment]
версия Ubuntu 20.04.3 LTS

**Comment by PanPrizrak** [comment]
Подскажите пожалуйста ка запустить

**Comment by CrazyXacker** [comment]
@PanPrizrak на почту запрошенные файлы отсылали?

**Comment by vanja-san** [comment]
@CrazyXacker java должна быть установлена? У меня просто есть портативные версии прописанные в ENV, но не уверен что это то что нужно. И можно ли запустить ваше приложение через консоль `java -l anilabx.jar`?

**Comment by CrazyXacker** [comment]
@vanja-san java не нужна, хотя единожды было сообщение о том, что переустановка java (и/или смена ее версии) решала проблему с запуском (хотя это и странно. приложение полностью самостоятельное).
запускать через консоль, как вы показали, нельзя. это не java приложение в обычном его понимании

**Comment by uranius666** [comment]
На федоре:
sudo chmod +x имя_файла
sudo dnf -y install https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm
sudo dnf -y install https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
sudo dnf -y install ffmpeg
sudo dnf -y install ffmpeg-devel
После этого все запускается

**Comment by PanPrizrak** [comment]
сб, 18 сент. 2021 г., 17:22 uranius666 ***@***.***>:

**Comment by CrazyXacker** [comment]
@uranius666 честно говоря, я очень сильно удивлен, ведь в приложении нет никаких зависимостей от ffmpeg. видимо, сам ffmpeg тянет какую-то из необходимых зависимостей. в любом случае, спасибо за вариант решения

**Comment by uranius666** [comment]
При запуске выдавало такую ошибку: /AniLabXLite_linux64: error while loading shared libraries: libavcodec.so.58: cannot open shared object file: No such file or directory

**Comment by CrazyXacker** [comment]
@uranius666 вот оно как. у других пользователей, зачастую, проблема иного характера (не удалось создать pipeline для рендера UI)

**Comment by uranius666** [comment]
> проблема иного характера

Сколько дистрибутивов столько и проблем))

**Comment by ShinyZero0** [comment]
На федора 36 ffmpeg установил, сделал файл исполняемым и переместил в новую папку, когда запускаю через терминал (и без него) ничего не появляется, кроме папок cache и database, Что делать?

**Comment by CrazyXacker** [comment]
@ShinyZero0 создайте рядом с бинарником пустой файл log, запустите приложение и отправьте сюда файл error.log. Если, конечно, проблема еще актуальна

**Comment by ShinyZero0** [comment]
@CrazyXacker 
[err.txt](https://github.com/CrazyXacker/AniLabX-Lite-Desktop/files/9077258/err.txt)
Такой появился

**Comment by ShinyZero0** [comment]
Там что-то про Java написано, я ее с офф. сайта ставил чтобы в майнкрафт играть

**Comment by CrazyXacker** [comment]
@ShinyZero0 к сожалению, данная проблема не лечится

`Graphics Device initialization failed for :  es2, sw
Error initializing QuantumRenderer: no suitable pipeline found
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found`

причины ее возникновения неизвестны и отладке она никак не подлежит. увы
единственное что я знаю, так это то, что на системах с musl (вместо дефолтного libc) работать точно не будет

**Comment by orkonung** [comment]
@CrazyXacker Здравствуйте, у меня появляется вот такая ошибка 
![image](https://user-images.githubusercontent.com/55378532/185774710-3ad5d682-6db8-42b4-ba99-32cb74aba8af.png)
создаются две папки, cache пустой, а в database только один файл anilabx.db.
win10 x64

**Comment by CrazyXacker** [comment]
Исправлено. https://github.com/CrazyXacker/AniLabX-Lite-Desktop/releases/tag/v1.6_linux_fix
