### ISSUE TITLE
18+ Empty List

### ISSUE THREAD

**Issue by hytebackup** [CrazyXacker/AniLabX-Lite-Desktop#8]
Большая часть контента с 18+ показывает Empty list

**Comment by CrazyXacker** [comment]
@hytebackup приложение использует два каталога для доступа к контенту: Shikimori (в роли самого каталога, который вы видите в приложении) и сторонний сервис с видео, который "привязывается" к каталогу Shikimori. Так вот, этот сторонний сервис не гарантирует наличие у себя контента. Что и случилось у вас
